font:
  normal:
    family: Pragmata Pro
    style: Regular

  bold:
    family: Pragmata Pro
    style: Bold

  italic:
    family: Pragmata Pro
    style: Italic

  bold_italic:
    family: Pragmata Pro
    style: Bold Italic

colors:
   # Default colors
   primary:
     background: '#000000'
     foreground: '#ffffff'
   # Normal colors
   normal:
     black:   '#000000'
     red:     '#cd0000'
     green:   '#00cd00'
     yellow:  '#cdcd00'
     blue:    '#0000ee'
     magenta: '#cd00cd'
     cyan:    '#00cdcd'
     white:   '#e5e5e5'

   # Bright colors
   bright:
     black:   '#7f7f7f'
     red:     '#ff0000'
     green:   '#00ff00'
     yellow:  '#ffff00'
     blue:    '#5c5cff'
     magenta: '#ff00ff'
     cyan:    '#00ffff'
     white:   '#ffffff'